### ISSUE TITLE
Unable to properly clone this repository

### ISSUE THREAD

**Issue by PureTryOut** [ubports/geonames#1]
I've been trying to get the full source in this repo today, which is basically impossible. The `.tar.gz` generated by Github doesn't work with Git LFS, so you have to use Git to clone the source.
However, even cloning (*with* Git LFS installed) is impossible, as I get the following:

```
Error downloading object: data/alternateNames.txt (ba6ce17): Smudge error: Error downloading data/alternateNames.txt (ba6ce17564e83fa53270e482d319ed9442d23fe347e5fbb331b0aff6ee7122de): batch response: This repository is over its data quota. Purchase more data packs to restore access.
```

It would be nice if this file could either be provided from outside this repository, or the above error gets resolved.

@vanyasem can shed some more light on this.

**Comment by vanyasem** [comment]
@mariogrip pointed out that a CI builds a proper tarball with this file included https://ci.ubports.com/job/geonames/job/xenial/3/artifact/geonames_0.3+ubports1+0~20180310073020.3~1.gbp5d77e8.tar.gz

**Comment by vanyasem** [comment]
In case someone urgently needs it, i uploaded it to https://unity8.mynameisivan.ru/alternateNames.txt

sha256sum alternateNames.txt `ba6ce17564e83fa53270e482d319ed9442d23fe347e5fbb331b0aff6ee7122de`

**Comment by vanyasem** [comment]
This issue is directly related https://github.com/git-lfs/git-lfs/issues/903

**Comment by vanyasem** [comment]
Made a fork with git-lfs disabled: https://github.com/vanyasem/geonames
(Be sure to manually copy the file from my mirror to `data/`)

**Comment by abhishek9650** [comment]
I second this, we need a fix

**Comment by vanyasem** [comment]
Sent a copy of this file to telegram https://t.me/UBports_Unity8/9365 because my mirror was dead for some time

**Comment by vanyasem** [comment]
Made an another fork with git-lfs disabled and the 400mb file embedded in the repo (painfully slow): https://bitbucket.org/vanyasem/geonames

**Comment by gber** [comment]
This project has been migrated to https://gitlab.com/ubports/development/core/geonames. If this is still an issue with the new repository, please file a new bug at https://gitlab.com/ubports/development/core/geonames/-/issues
